using ImagesGenerator.Models;

namespace ImagesGenerator.Services;

public interface ISubjectService
{
    IReadOnlyList<Subject> GetSubjects();
}

public class SubjectService : ISubjectService
{
    private readonly List<Subject> _subjects = new()
    {
        //new Subject("00", "Sauce"),
        //new Subject("01", "Seed"),
        //new Subject("02", "Sun"),
        //new Subject("03", "Sumo"),
        //new Subject("04", "Sierra"),
        //new Subject("05", "Soil"),
        //new Subject("06", "Sewage"),
        //new Subject("07", "Sky"),
        //new Subject("08", "Sofa"),
        //new Subject("09", "Soap"),
        //new Subject("10", "Daisy"),
        //new Subject("11", "Tattoo"),
        //new Subject("12", "Tuna"),
        new Subject("13", "Dome"),
        //new Subject("14", "Diary"),
        new Subject("15", "Tail"),
        new Subject("16", "Dish"),
        new Subject("17", "Dog"),
        new Subject("18", "Dove"),
        new Subject("19", "Tuba"),
        //new Subject("20", "Nose"),
        //new Subject("21", "Net"),
        new Subject("22", "Onion"),
        //new Subject("23", "Enemy"),
        //new Subject("24", "Winery"),
        new Subject("25", "Nail"),
        //new Subject("26", "Nacho"),
        //new Subject("27", "Neck"),
        new Subject("28", "Knife"),
        new Subject("29", "Honeybee"),
        // new Subject("30", "Mouse"),
        // new Subject("31", "Meadow"),
        // new Subject("32", "Moon"),
        // new Subject("33", "Mummy"),
        // new Subject("34", "Emery"),
        // new Subject("35", "Mole"),
        // new Subject("36", "Match"),
        // new Subject("37", "Mug"),
        // new Subject("38", "Movie"),
        // new Subject("39", "Map"),
        // new Subject("40", "Rice"),
        // new Subject("41", "Road"),
        // new Subject("42", "Rain"),
        // new Subject("43", "Rum"),
        // new Subject("44", "Aurora"),
        // new Subject("45", "Railway"),
        // new Subject("46", "Roach"),
        // new Subject("47", "Rag"),
        // new Subject("48", "Roof"),
        // new Subject("49", "Rope"),
        // new Subject("50", "Louse"),
        // new Subject("51", "Lady"),
        // new Subject("52", "Lion"),
        // new Subject("53", "Lime"),
        // new Subject("54", "Lorry"),
        // new Subject("55", "Lily"),
        // new Subject("56", "Leech"),
        // new Subject("57", "Leg"),
        // new Subject("58", "Lava"),
        // new Subject("59", "Lip"),
        // new Subject("60", "Cheese"),
        // new Subject("61", "Cheetah"),
        // new Subject("62", "Chin"),
        // new Subject("63", "Gem"),
        // new Subject("64", "Shrew"),
        // new Subject("65", "Chilli"),
        // new Subject("66", "ChaCha"),
        // new Subject("67", "Chick"),
        // new Subject("68", "Chef"),
        // new Subject("69", "Jeep"),
        // new Subject("70", "Goose"),
        // new Subject("71", "Cat"),
        // new Subject("72", "Coin"),
        // new Subject("73", "Game"),
        // new Subject("74", "Crow"),
        // new Subject("75", "Clay"),
        // new Subject("76", "Cage"),
        // new Subject("77", "Cake"),
        // new Subject("78", "Cave"),
        // new Subject("79", "Cube"),
        // new Subject("80", "Vase"),
        // new Subject("81", "Video"),
        // new Subject("82", "Fan"),
        // new Subject("83", "Ovum"),
        // new Subject("84", "Fairy"),
        // new Subject("85", "Fool"),
        // new Subject("86", "Veggie"),
        // new Subject("87", "Fig"),
        // new Subject("88", "Fife"),
        // new Subject("89", "Vibe"),
        // new Subject("90", "Boss"),
        // new Subject("91", "Bead"),
        // new Subject("92", "Pony"),
        // new Subject("93", "Puma"),
        // new Subject("94", "Berry"),
        // new Subject("95", "Bell"),
        // new Subject("96", "Pouch"),
        // new Subject("97", "Bike"),
        // new Subject("98", "Beef"),
        // new Subject("99", "Pipe"),
    };
    
    public IReadOnlyList<Subject> GetSubjects() => _subjects.AsReadOnly();
}